apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitydevopscapstone-blue
  labels:
    app: udacitydevopscapstone-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacitydevopscapstone-blue
  template:
    metadata: 
      labels:
        app: udacitydevopscapstone-blue
    spec:
      containers:
        - name: udacitydevopscapstone-blue
          image: abayman/udacitydevopscapstone-blue
          ports:
          - containerPort: 5000